//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guidant.Demo.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortfolioSecurity
    {
        public int PortfolioId { get; set; }
        public int SecurityId { get; set; }
        public int Count { get; set; }
    
        public virtual Portfolio Portfolio { get; set; }
        public virtual Security Security { get; set; }
    }
}
